l1: Fix warning by logging acc_delay
The acc_delay value is computed but not used, resulting in a warning.

This commit adds a logging message it case the function is executed
to make the warning disappear. It also adds a CPP warning to remind
of the incomplete implementation.

Addresses:
  sysmo_l1_if.c:226:10: error: variable ‘acc_delay’ set but not used
[-Werror=unused-but-set-variable]

Sponsored-by: On-Waves ehf